### ISSUE TITLE
trooble to find GSL library

### ISSUE THREAD

**Issue by El-Castor** [TheJacksonLaboratory/sci#1]
Hi , 

Thanks for this usefull tool, I'm trying to test it on my hiC data but I have some trooble to install it. 

When It do python setup.py I have this error message : 

`
/usr/bin/ld: /tmp/ccRW8Yq1.o: in function `TrainLINEThread(void*)':
line.cpp:(.text+0x159e): undefined reference to `gsl_rng_uniform'
/usr/bin/ld: line.cpp:(.text+0x15b5): undefined reference to `gsl_rng_uniform'
/usr/bin/ld: /tmp/ccRW8Yq1.o: in function `TrainLINE()':
line.cpp:(.text+0x1aca): undefined reference to `gsl_rng_env_setup'
/usr/bin/ld: line.cpp:(.text+0x1ad1): undefined reference to `gsl_rng_rand48'
/usr/bin/ld: line.cpp:(.text+0x1ae7): undefined reference to `gsl_rng_alloc'
/usr/bin/ld: line.cpp:(.text+0x1b02): undefined reference to `gsl_rng_set'
collect2: error: ld returned 1 exit status
LINE compilation has failed.Please make sure to install GSL library
`

I understand that the tool doesn't fin my gsl library. but the fact is taht I have install it on My conda environment, see below : 

`
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
blas                      1.1                    openblas    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
certifi                   2016.9.26                py27_0    conda-forge
gsl                       2.6                  h294904e_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
libblas                   3.8.0               11_openblas    conda-forge
libcblas                  3.8.0               11_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
libgomp                   9.2.0                h24d8f2e_2    conda-forge
liblapack                 3.8.0               11_openblas    conda-forge
libopenblas               0.3.6                h5a2b251_2  
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.16.5           py27h95a1406_0    conda-forge
openblas                  0.3.3             h9ac9557_1001    conda-forge
openssl                   1.1.1f               h516909a_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
python                    2.7.15          h5a48372_1011_cpython    conda-forge
python_abi                2.7                    1_cp27mu    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
scikit-learn              0.20.4          py27_blas_openblashebff5e3_0  [blas_openblas]  conda-forge
scipy                     1.2.1           py27_blas_openblash1522bff_0  [blas_openblas]  conda-forge
setuptools                44.0.0                   py27_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tqdm                      4.45.0             pyh9f0ad1d_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
`

More over My library are in the lib folder of my environment : 
Running this command : ls <PATH_TO_MY_LIB> | grep "gsl" | head
`
libgsl.a
libgslcblas.a
libgslcblas.so
libgslcblas.so.0
libgslcblas.so.0.0.0
libgsl.so
libgsl.so.25
libgsl.so.25.0.0

`
So I don't understand why It doesn't find th gsl lib, have you got an Idea please ?

thanks in advance

**Comment by AshoorH** [comment]
Hi, 

It seems there is an issue in your environment setup. The  C++ linker does not recognize where your GSL library is installed. 
In the `setup.py` you can add `-L <path/to/GSL> ` to the compilation function. 

I hope this helps.

**Comment by jos4uke** [comment]
Hi 
I made some fixes to the install doc in this pull request #2 
to help 
Best

**Comment by El-Castor** [comment]
Thanks !
@ AshoorH I have an another, after sci installation I don't find the folder called Input_sample in the directory, where I can find it?
I've try your soft on my data in differents resolutions to understand how It works.  But I don't know if I have really understand how to used it. I'm wondering, which hic map resolution do used in input for the compartment founding ?More over, to underlie sub-domains I used the hirarchical constrain clustering using the CONISS method. With It I can find the differents compartment type. But with SCI I have not sub-compartement that are related to inactive global compartment and active local compartment. Do you have any idea on it ?
Thanks in advance

**Comment by AshoorH** [comment]
@El-Castor 
SCI uses inter-chromosomes interactions to predict sub-compartments, it requires data to have relatively high read coverage in order to predict sub-compartments. If your inter-chromosomes interaction data quality is low then SCI will not be able to predict such sub-compartments.

**Comment by El-Castor** [comment]
I don't find the folder called Input_sample in the directory, where I can find it?
which Hi-C map resolution do used in input for the compartment founding, you didn't specified it on your paper ?
